// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file UserChatTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen.
 */

#include "UserChatTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "UserChat.hpp"


using namespace eprosima::fastdds::dds::xtypes;

// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_UserChat_type_identifier(
        TypeIdentifierPair& type_ids_UserChat)
{

    ReturnCode_t return_code_UserChat {eprosima::fastdds::dds::RETCODE_OK};
    return_code_UserChat =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "UserChat", type_ids_UserChat);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_UserChat)
    {
        StructTypeFlag struct_flags_UserChat = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_UserChat = "UserChat";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_UserChat;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_UserChat;
        CompleteTypeDetail detail_UserChat = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_UserChat, ann_custom_UserChat, type_name_UserChat.to_string());
        CompleteStructHeader header_UserChat;
        header_UserChat = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_UserChat);
        CompleteStructMemberSeq member_seq_UserChat;
        {
            TypeIdentifierPair type_ids_index;
            ReturnCode_t return_code_index {eprosima::fastdds::dds::RETCODE_OK};
            return_code_index =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint32_t", type_ids_index);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_index)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "index Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_index = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_index = 0x00000000;
            bool common_index_ec {false};
            CommonStructMember common_index {TypeObjectUtils::build_common_struct_member(member_id_index, member_flags_index, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_index, common_index_ec))};
            if (!common_index_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure index member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_index = "index";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_index;
            ann_custom_UserChat.reset();
            CompleteMemberDetail detail_index = TypeObjectUtils::build_complete_member_detail(name_index, member_ann_builtin_index, ann_custom_UserChat);
            CompleteStructMember member_index = TypeObjectUtils::build_complete_struct_member(common_index, detail_index);
            TypeObjectUtils::add_complete_struct_member(member_seq_UserChat, member_index);
        }
        {
            TypeIdentifierPair type_ids_username;
            ReturnCode_t return_code_username {eprosima::fastdds::dds::RETCODE_OK};
            return_code_username =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_username);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_username)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_username))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_username = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_username = 0x00000001;
            bool common_username_ec {false};
            CommonStructMember common_username {TypeObjectUtils::build_common_struct_member(member_id_username, member_flags_username, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_username, common_username_ec))};
            if (!common_username_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure username member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_username = "username";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_username;
            ann_custom_UserChat.reset();
            CompleteMemberDetail detail_username = TypeObjectUtils::build_complete_member_detail(name_username, member_ann_builtin_username, ann_custom_UserChat);
            CompleteStructMember member_username = TypeObjectUtils::build_complete_struct_member(common_username, detail_username);
            TypeObjectUtils::add_complete_struct_member(member_seq_UserChat, member_username);
        }
        {
            TypeIdentifierPair type_ids_message;
            ReturnCode_t return_code_message {eprosima::fastdds::dds::RETCODE_OK};
            return_code_message =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_message);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_message)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_message))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_message = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_message = 0x00000002;
            bool common_message_ec {false};
            CommonStructMember common_message {TypeObjectUtils::build_common_struct_member(member_id_message, member_flags_message, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_message, common_message_ec))};
            if (!common_message_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure message member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_message = "message";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_message;
            ann_custom_UserChat.reset();
            CompleteMemberDetail detail_message = TypeObjectUtils::build_complete_member_detail(name_message, member_ann_builtin_message, ann_custom_UserChat);
            CompleteStructMember member_message = TypeObjectUtils::build_complete_struct_member(common_message, detail_message);
            TypeObjectUtils::add_complete_struct_member(member_seq_UserChat, member_message);
        }
        {
            TypeIdentifierPair type_ids_picture;
            ReturnCode_t return_code_picture {eprosima::fastdds::dds::RETCODE_OK};
            return_code_picture =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int32_t", type_ids_picture);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_picture)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "picture Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_picture = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_picture = 0x00000003;
            bool common_picture_ec {false};
            CommonStructMember common_picture {TypeObjectUtils::build_common_struct_member(member_id_picture, member_flags_picture, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_picture, common_picture_ec))};
            if (!common_picture_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure picture member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_picture = "picture";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_picture;
            ann_custom_UserChat.reset();
            CompleteMemberDetail detail_picture = TypeObjectUtils::build_complete_member_detail(name_picture, member_ann_builtin_picture, ann_custom_UserChat);
            CompleteStructMember member_picture = TypeObjectUtils::build_complete_struct_member(common_picture, detail_picture);
            TypeObjectUtils::add_complete_struct_member(member_seq_UserChat, member_picture);
        }
        CompleteStructType struct_type_UserChat = TypeObjectUtils::build_complete_struct_type(struct_flags_UserChat, header_UserChat, member_seq_UserChat);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_UserChat, type_name_UserChat.to_string(), type_ids_UserChat))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "UserChat already registered in TypeObjectRegistry for a different type.");
        }
    }
}

